#include "util/color.h"

struct colormap cm_rainbow = {
    .name = "Rainbow",
    .n_points = 7,
    .state = COLORMAP_STATE_UNINITIALIZED,
    .points = {
        { .x = 0.,
          .y = {1., 0., 0., 1.},
          .gamma = 1.,
        },
        { .x = 1./6.,
          .y = {1., 1., 0., 1.},
          .gamma = 1.,
        },
        { .x = 2./6.,
          .y = {0., 1., 0., 1.},
          .gamma = 1.,
        },
        { .x = 3./6.,
          .y = {0., 1., 1., 1.},
          .gamma = 1.,
        },
        { .x = 4./6.,
          .y = {0., 0., 1., 1.},
          .gamma = 1.,
        },
        { .x = 5./6.,
          .y = {1., 0., 1., 1.},
          .gamma = 1.,
        },
        { .x = 1.,
          .y = {1., 0., 0., 1.},
          .gamma = 1.,
        },
    },
};

struct colormap cm_rainbow_edged = {
    .name = "Rainbow Edged",
    .n_points = 8,
    .state = COLORMAP_STATE_UNINITIALIZED,
    .points = {
        { .x = 0.0,
          .y = {0., 0., 0., 1.},
          .gamma = 1.,
        },
        { .x = 0.05,
          .y = {1., 0., 0., 1.},
          .gamma = 1.,
        },
        { .x = .2,
          .y = {1., 1., 0., 1.},
          .gamma = 1.,
        },
        { .x = .4,
          .y = {0., 1., 0., 1.},
          .gamma = 1.,
        },
        { .x = .6,
          .y = {0., 1., 1., 1.},
          .gamma = 1.,
        },
        { .x = .8,
          .y = {0., 0., 1., 1.},
          .gamma = 1.,
        },
        { .x = 0.95,
          .y = {1., 0., 1., 1.},
          .gamma = 1.,
        },
        { .x = 1.0,
          .y = {1., 1., 1., 1.},
          .gamma = 1.,
        },
    },
};

struct colormap cm_rainbow_equal = {
    .name = "Rainbow Equal",
    .n_points = 7,
    .state = COLORMAP_STATE_UNINITIALIZED,
    .points = {
        { .x = 0.,
          .y = {1., 0., 0., 1.},
          .gamma = 1.,
        },
        { .x = 1./6.,
          .y = {0.5, 0.5, 0., 1.},
          .gamma = 1.,
        },
        { .x = 2./6.,
          .y = {0., 1., 0., 1.},
          .gamma = 1.,
        },
        { .x = 3./6.,
          .y = {0., 0.5, 0.5, 1.},
          .gamma = 1.,
        },
        { .x = 4./6.,
          .y = {0., 0., 1., 1.},
          .gamma = 1.,
        },
        { .x = 5./6.,
          .y = {0.5, 0., 0.5, 1.},
          .gamma = 1.,
        },
        { .x = 1.,
          .y = {1., 0., 0., 1.},
          .gamma = 1.,
        },
    },
};

struct colormap cm_jet = {
    .name = "Jet",
    .n_points = 6,
    .state = COLORMAP_STATE_UNINITIALIZED,
    .points = {
        { .x = 0.00,
          .y = {0.5, 0.0, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.10,
          .y = {1.0, 0.0, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.35,
          .y = {1.0, 1.0, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.64,
          .y = {0.0, 1.0, 1.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.89,
          .y = {0.0, 0.0, 1.0, 1.},
          .gamma = 1.,
        },
        { .x = 1.00,
          .y = {0.0, 0.0, 0.5, 1.},
          .gamma = 1.,
        },
    },
};

struct colormap cm_hot = {
    .name = "Hot",
    .n_points = 5,
    .state = COLORMAP_STATE_UNINITIALIZED,
    .points = {
        { .x = 0.00,
          .y = {0.0, 0.0, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.30,
          .y = {1.0, 0.0, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.55,
          .y = {0.8, 0.5, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.70,
          .y = {1.0, 1.0, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 1.00,
          .y = {1.0, 1.0, 1.0, 1.},
          .gamma = 1.,
        },
    },
};

struct colormap cm_cyan = {
    .name = "Ocean",
    .n_points = 6,
    .state = COLORMAP_STATE_UNINITIALIZED,
    .points = {
        { .x = 0.00,
          .y = {0.0, 0.2, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.10,
          .y = {0.0, 0.5, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.20,
          .y = {0.0, 0.8, 0.1, 1.},
          .gamma = 1.,
        },
        { .x = 0.50,
          .y = {0.0, 0.1, 0.5, 1.},
          .gamma = 1.,
        },
        { .x = 0.80,
          .y = {0.0, 1.0, 1.0, 1.},
          .gamma = 1.,
        },
        { .x = 1.00,
          .y = {1.0, 1.0, 1.0, 1.},
          .gamma = 1.,
        },
    },
};

struct colormap cm_purple = {
    .name = "Purple",
    .n_points = 6,
    .state = COLORMAP_STATE_UNINITIALIZED,
    .points = {
        { .x = 0.00,
          .y = {1.0, 0.0, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.25,
          .y = {0.5, 0.0, 0.2, 1.},
          .gamma = 1.,
        },
        { .x = 0.50,
          .y = {0.8, 0.0, 1.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.75,
          .y = {0.0, 0.0, 1.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.90,
          .y = {0.1, 0.0, 0.8, 1.},
          .gamma = 1.,
        },
        { .x = 1.00,
          .y = {0.6, 0.4, 1.0, 1.},
          .gamma = 1.,
        },
    },
};

struct colormap cm_stoplight = {
    .name = "Stoplight",
    .n_points = 5,
    .state = COLORMAP_STATE_UNINITIALIZED,
    .points = {
        { .x = 0.00,
          .y = {0.2, 0.0, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.15,
          .y = {1.0, 0.0, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.50,
          .y = {1.0, 0.7, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.85,
          .y = {0.0, 1.0, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 1.00,
          .y = {0.0, 0.2, 0.0, 1.},
          .gamma = 1.,
        },
    },
};

struct colormap cm_bright = {
    .name = "Bright",
    .n_points = 5,
    .state = COLORMAP_STATE_UNINITIALIZED,
    .points = {
        { .x = 0.00,
          .y = {0.8, 0.0, 0.8, 1.},
          .gamma = 1.,
        },
        { .x = 0.15,
          .y = {0.6, 0.1, 0.9, 1.},
          .gamma = 1.,
        },
        { .x = 0.40,
          .y = {0.0, 0.4, 1.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.75,
          .y = {0.0, 1.0, 0.3, 1.},
          .gamma = 1.,
        },
        { .x = 1.00,
          .y = {1.0, 0.8, 0.0, 1.},
          .gamma = 1.,
        },
    },
};

struct colormap cm_goth = {
    .name = "Goth",
    .n_points = 5,
    .state = COLORMAP_STATE_UNINITIALIZED,
    .points = {
        { .x = 0.00,
          .y = {0.0, 0.0, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.25,
          .y = {1.0, 1.0, 1.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.50,
          .y = {0.0, 0.0, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 0.75,
          .y = {1.0, 0.0, 0.0, 1.},
          .gamma = 1.,
        },
        { .x = 1.00,
          .y = {0.0, 0.0, 0.0, 1.},
          .gamma = 1.,
        },
    },
};
